/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-05-07 06:48:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.MemberDao;

public final class top_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(1);
    _jspx_imports_classes.add("member.MemberDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("top.jsp<br>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/script.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("    $('#searchByBtitle').click(function(){\r\n");
      out.write("        var btitle = $('input[name = btitle]').val();\r\n");
      out.write("        \r\n");
      out.write("        if(btitle == \"\") {\r\n");
      out.write("            alert(\"검색하고 싶은 도서명을 입력하세요\");\r\n");
      out.write("            $('input[name = btitle]').focus();\r\n");
      out.write("            return false;\r\n");
      out.write("        } else {\r\n");
      out.write("            return true; // 입력값이 비어 있지 않으면 검색 동작 실행\r\n");
      out.write("        }\r\n");
      out.write("    }); //submit 클릭\r\n");
      out.write("}); //ready\r\n");
      out.write("</script>\r\n");

    String id = (String)session.getAttribute("id");
	String password = (String)session.getAttribute("password");
	String mname = (String)session.getAttribute("mname");
	
	MemberDao mdao = MemberDao.getInstance();
	int mnum = mdao.findmnum(id);
	
    if(id == null) {
    	System.out.println("<top.jsp> null");

      out.write("      \r\n");
      out.write("    <body align = \"center\">\r\n");
      out.write("    <table border = 1 align = \"right\">\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td><a href = \"");
      out.print( request.getContextPath() );
      out.write("/login/login.jsp\">로그인</a></td>\r\n");
      out.write("            <td><a href = \"");
      out.print( request.getContextPath() );
      out.write("/user/ManageAccount/canIInsert.jsp\">회원가입</a></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("    <br>\r\n");
      out.write("    <br>\r\n");
      out.write("    <table border = 1 align = \"center\" width = \"90%\">\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td width = \"20%\">\r\n");
      out.write("                여기에 이미지 넣어야 함\r\n");
      out.write("            </td>\r\n");
      out.write("            <td width = \"80%\" align = \"center\">\r\n");
      out.write("                <form action = \"user/SearchBook/searchBookByBtitleProc.jsp\">\r\n");
      out.write("                    <input type = \"text\" name = \"btitle\">\r\n");
      out.write("                    <input type = \"submit\" id = \"searchByBtitle\" value = \"검색\">\r\n");
      out.write("                </form>\r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("    <table border = 1 align = \"center\" width = \"90%\">\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>회사 소개</td>\r\n");
      out.write("            <td>도서 검색</td>\r\n");
      out.write("            <td>행사 안내</td>\r\n");
      out.write("            <td>묻고 답하기</td>\r\n");
      out.write("            <td>개인정보</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
  } else { 
		if(id.startsWith("admin")) {
			System.out.println("session으로 설정한 adminid : " + id);

      out.write("			<body align = \"center\">\r\n");
      out.write("			    <table border = 1 align = \"right\">\r\n");
      out.write("			        <tr>\r\n");
      out.write("			        	<td>");
      out.print( mname );
      out.write("님</td>\r\n");
      out.write("			            <td><a href = \"");
      out.print( request.getContextPath() );
      out.write("/login/logout.jsp\">로그아웃</a></td>\r\n");
      out.write("			            <td><a href = \"");
      out.print( request.getContextPath() );
      out.write("/user/ManageAccount/showMyAccount.jsp?id=");
      out.print( id );
      out.write("&password=");
      out.print( password );
      out.write("\">내 정보</a></td>\r\n");
      out.write("			        </tr>\r\n");
      out.write("			    </table>\r\n");
      out.write("			    <br>\r\n");
      out.write("			    <br>\r\n");
      out.write("			    <table border = 1 align = \"center\" width = \"90%\">\r\n");
      out.write("			        <tr>\r\n");
      out.write("			            <td width = \"20%\">\r\n");
      out.write("			                여기에 이미지 넣어야 함\r\n");
      out.write("			            </td>\r\n");
      out.write("			            <td width = \"80%\" align = \"center\">\r\n");
      out.write("			                <form action = \"user/SearchBook/searchBookByBtitle.jsp\">\r\n");
      out.write("			                    <input type = \"text\" name = \"btitle\">\r\n");
      out.write("			                    <input type = \"submit\" id = \"searchByBtitle\" value = \"검색\">\r\n");
      out.write("			                </form>\r\n");
      out.write("			            </td>\r\n");
      out.write("			        </tr>\r\n");
      out.write("			    </table>\r\n");
      out.write("			    <table border = 1 align = \"center\" width = \"90%\">\r\n");
      out.write("			        <tr>\r\n");
      out.write("			            <td>회사 소개</td>\r\n");
      out.write("			            <td>\r\n");
      out.write("			            	<a href = \"");
      out.print( request.getContextPath() );
      out.write("/admin/ManageBook/showBook.jsp\">\r\n");
      out.write("			           			도서 관리\r\n");
      out.write("			           		</a>\r\n");
      out.write("			           		\r\n");
      out.write("			           		<a href = \"");
      out.print( request.getContextPath() );
      out.write("/admin/ManageBook/showBookByCategory.jsp\">\r\n");
      out.write("			           			카테고리별 도서 관리\r\n");
      out.write("			           		</a>\r\n");
      out.write("			           		\r\n");
      out.write("			           		<a href = \"");
      out.print( request.getContextPath() );
      out.write("/admin/ManageBook/showBookByBpubyear.jsp\">\r\n");
      out.write("			           			연도별 도서 관리\r\n");
      out.write("			           		</a>\r\n");
      out.write("			            </td>\r\n");
      out.write("			            <td>\r\n");
      out.write("			           		<a href = \"");
      out.print( request.getContextPath() );
      out.write("/admin/ManageMember/showMember.jsp\">\r\n");
      out.write("			            		회원 관리\r\n");
      out.write("			            	</a>\r\n");
      out.write("			            </td>\r\n");
      out.write("			            <td>\r\n");
      out.write("			            	묻고 답하기\r\n");
      out.write("			            </td>\r\n");
      out.write("			            <td>\r\n");
      out.write("			            	개인정보\r\n");
      out.write("			            </td>\r\n");
      out.write("			        </tr>\r\n");
      out.write("			    </table>\r\n");
      out.write("			</body>\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
		} else {
   		 System.out.println("session으로 설정한 id : " + id);

      out.write("			<body align = \"center\">\r\n");
      out.write("			    <table border = 1 align = \"right\">\r\n");
      out.write("			        <tr>\r\n");
      out.write("			        	<td>");
      out.print( mname );
      out.write("님</td>\r\n");
      out.write("			            <td><a href = \"");
      out.print( request.getContextPath() );
      out.write("/login/logout.jsp\">로그아웃</a></td>\r\n");
      out.write("			            <td><a href = \"");
      out.print( request.getContextPath() );
      out.write("/user/ManageAccount/showMyAccount.jsp?id=");
      out.print( id );
      out.write("&password=");
      out.print( password );
      out.write("\">내 정보</a></td>\r\n");
      out.write("			        </tr>\r\n");
      out.write("			    </table>\r\n");
      out.write("			    <br>\r\n");
      out.write("			    <br>\r\n");
      out.write("			    <table border = 1 align = \"center\" width = \"90%\">\r\n");
      out.write("			        <tr>\r\n");
      out.write("			            <td width = \"20%\">\r\n");
      out.write("			                여기에 이미지 넣어야 함\r\n");
      out.write("			            </td>\r\n");
      out.write("			            <td width = \"80%\" align = \"center\">\r\n");
      out.write("			                <form action = \"");
      out.print( request.getContextPath() );
      out.write("/user/SearchBook/searchBookByBtitle.jsp\">\r\n");
      out.write("			                    <input type = \"text\" name = \"btitle\">\r\n");
      out.write("			                    <input type = \"submit\" id = \"searchByBtitle\" value = \"검색\">\r\n");
      out.write("			                </form>\r\n");
      out.write("			            </td>\r\n");
      out.write("			        </tr>\r\n");
      out.write("			    </table>\r\n");
      out.write("			    <table border = 1 align = \"center\" width = \"90%\">\r\n");
      out.write("			        <tr>\r\n");
      out.write("			            <td>회사 소개</td>\r\n");
      out.write("					<td align=\"center\">\r\n");
      out.write("					    <ul>\r\n");
      out.write("					        <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/SearchBook/searchBookAll.jsp\">모든 도서 보기</a></li>\r\n");
      out.write("					        <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/SearchBook/searchBookByBtitle.jsp\">제목별 검색</a></li>\r\n");
      out.write("					        <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/SearchBook/searchBookByCategory.jsp\">카테고리별 검색</a></li>\r\n");
      out.write("					        <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/SearchBook/searchBookMost.jsp\">베스트셀러</a></li>\r\n");
      out.write("					        <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/SearchBook/searchBookNew.jsp\">신간</a></li>\r\n");
      out.write("					    </ul>\r\n");
      out.write("					</td>\r\n");
      out.write("					<td>\r\n");
      out.write("					    <ul>\r\n");
      out.write("					        <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/BorrowBook/borrowList.jsp\">내 대출 도서 보기</a></li>\r\n");
      out.write("					        <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/ReserveBook/reserveList.jsp\">내 예약 도서 보기</a></li>\r\n");
      out.write("					    </ul>\r\n");
      out.write("					</td>\r\n");
      out.write("			            <td>행사 안내</td>\r\n");
      out.write("			            <td>\r\n");
      out.write("			            	<ul>							\r\n");
      out.write("							    <li>자주묻는 질문</li>\r\n");
      out.write("							    <li>묻고답하기</li>\r\n");
      out.write("							</ul>\r\n");
      out.write("			            </td>\r\n");
      out.write("			            <td>\r\n");
      out.write("							<ul>\r\n");
      out.write("						        <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/ManageAccount/showMyAccount.jsp?password=");
      out.print(password);
      out.write("\">내 정보 보기</a></li>\r\n");
      out.write("						        <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/ManageAccount/updateMyAccount.jsp\">내 정보 수정</a></li>\r\n");
      out.write("						        <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/ManageAccount/deleteMyAccount.jsp\">회원 탈퇴</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</td>\r\n");
      out.write("			        </tr>\r\n");
      out.write("			    </table>\r\n");
      out.write("			</body>\r\n");
		}

      out.write("\r\n");
      out.write("    \r\n");
  } 
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
