/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-05-08 09:53:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.MemberDao;

public final class findId_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/login/../../top.jsp", Long.valueOf(1715160700093L));
    _jspx_dependants.put("/login/../../bottom.jsp", Long.valueOf(1715159785267L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(1);
    _jspx_imports_classes.add("member.MemberDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/script.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("    $('#searchByBtitle').click(function(){\r\n");
      out.write("        var btitle = $('input[name = btitle]').val();\r\n");
      out.write("        \r\n");
      out.write("        if(btitle == \"\") {\r\n");
      out.write("            alert(\"검색하고 싶은 도서명을 입력하세요\");\r\n");
      out.write("            $('input[name = btitle]').focus();\r\n");
      out.write("            return false;\r\n");
      out.write("        } else {\r\n");
      out.write("            return true; // 입력값이 비어 있지 않으면 검색 동작 실행\r\n");
      out.write("        }\r\n");
      out.write("    }); //submit 클릭\r\n");
      out.write("}); //ready\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".menu-container {\r\n");
      out.write("    width: 90%;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-list {\r\n");
      out.write("    list-style: none;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    display: table;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-item {\r\n");
      out.write("    display: table-cell;\r\n");
      out.write("    margin-right: 20px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("    width: 20%; /* 각 항목의 너비를 20%로 설정 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-item a {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: #333;\r\n");
      out.write("    display: block;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    background-color: #f4f4f4;\r\n");
      out.write("    border: 1px solid #ccc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".submenu {\r\n");
      out.write("    display: none;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    background-color: #fff;\r\n");
      out.write("    border: 1px solid #ccc;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    width: 16.7%; /* 하위 목록의 너비를 100%로 설정 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-item:hover .submenu {\r\n");
      out.write("    display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".submenu li {\r\n");
      out.write("    display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".submenu li a {\r\n");
      out.write("    display: block;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".submenu li a:hover {\r\n");
      out.write("    background-color: #f4f4f4;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#search-container {\r\n");
      out.write("    width: 60%; /* 전체 너비의 90%로 설정 */\r\n");
      out.write("    margin: 0 auto; /* 가운데 정렬을 위해 왼쪽과 오른쪽에 자동 마진 추가 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#search-container input[type=\"text\"] {\r\n");
      out.write("    width: 80%; /* 검색 칸의 너비를 80%로 설정 */\r\n");
      out.write("    padding: 10px; /* 내부 여백 추가 */\r\n");
      out.write("    font-size: 16px; /* 글꼴 크기 설정 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#search-container input[type=\"submit\"] {\r\n");
      out.write("    width: 15%; /* 검색 버튼의 너비를 15%로 설정 */\r\n");
      out.write("    padding: 10px; /* 내부 여백 추가 */\r\n");
      out.write("    font-size: 16px; /* 글꼴 크기 설정 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#search-container img {\r\n");
      out.write("    max-width:15%; /* 이미지의 최대 너비를 전체의 25%로 설정 */\r\n");
      out.write("    height: auto; /* 가로 세로 비율을 유지하면서 이미지의 높이를 자동으로 조정 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 로그아웃 버튼 스타일 */\r\n");
      out.write(".login-button, .logout-button, .register-button {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    border: none;\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-button {\r\n");
      out.write("    background-color: #4CAF50;\r\n");
      out.write("    color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-button:hover {\r\n");
      out.write("    background-color: #45a049;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logout-button {\r\n");
      out.write("    background-color: #f44336;\r\n");
      out.write("    color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logout-button:hover {\r\n");
      out.write("    background-color: #d32f2f;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".register-button {\r\n");
      out.write("    background-color: #2196F3;\r\n");
      out.write("    color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".register-button:hover {\r\n");
      out.write("    background-color: #1e88e5;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".user-name {\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    color: #333;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("    .menu-container {\r\n");
      out.write("        font-family: Arial, sans-serif;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .menu-list {\r\n");
      out.write("        list-style-type: none;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .menu-item {\r\n");
      out.write("        background-color: #f8f9fa; /* 기본 배경색 */\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("        border-bottom: 1px solid #dee2e6;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .menu-item:hover {\r\n");
      out.write("        background-color: #e9ecef; /* 마우스 올릴 때 배경색 */\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .menu-item a {\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color: #212529;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .submenu {\r\n");
      out.write("        display: none;\r\n");
      out.write("        background-color: #fff;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        border: 1px solid #dee2e6;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .submenu li {\r\n");
      out.write("        padding: 8px 10px;\r\n");
      out.write("        border-bottom: 1px solid #dee2e6;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .submenu li:hover {\r\n");
      out.write("        background-color: #f8f9fa; /* 마우스 올릴 때 배경색 */\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .menu-item:hover .submenu {\r\n");
      out.write("        display: block;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");

	String id = (String)session.getAttribute("id");
	String password = (String)session.getAttribute("password");
	String mname = (String)session.getAttribute("mname");
	
	MemberDao mdao = MemberDao.getInstance();
	int mnum = mdao.findmnum(id);
	
	if(id == null) {
	    System.out.println("<top.jsp> null");

      out.write("      \r\n");
      out.write("		<body align = \"center\">\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("			<table align=\"center\" width=\"80%\">\r\n");
      out.write("			    <tr>\r\n");
      out.write("			        <td width=\"25%\">\r\n");
      out.write("			            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/main.jsp\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/image/도서관이미지.jpg\" id=\"library-image\" width=\"100%\"></a>\r\n");
      out.write("			        </td>\r\n");
      out.write("			        <td align=\"center\" id=\"search-container\">\r\n");
      out.write("			            <form action=\"");
      out.print( request.getContextPath() );
      out.write("/user/SearchBook/searchBookByBtitle.jsp\">\r\n");
      out.write("			                <input type=\"text\" name=\"btitle2\">\r\n");
      out.write("			                <input type=\"submit\" id=\"searchByBtitle\" value=\"검색\">\r\n");
      out.write("			            </form>\r\n");
      out.write("			        </td>\r\n");
      out.write("			        <td>\r\n");
      out.write("			            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/login/login.jsp\" class=\"login-button\">로그인</a>\r\n");
      out.write("			        </td>\r\n");
      out.write("			        <td>\r\n");
      out.write("			            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/ManageAccount/canIInsert.jsp\" class=\"register-button\">회원가입</a>\r\n");
      out.write("			        </td>\r\n");
      out.write("			    </tr>\r\n");
      out.write("			</table>\r\n");
      out.write("\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"menu-container\">\r\n");
      out.write("			    <ul class=\"menu-list\">\r\n");
      out.write("\r\n");
      out.write("			        <li class=\"menu-item\">\r\n");
      out.write("			            <a href=\"#\">도서</a>\r\n");
      out.write("			            <ul class=\"submenu\">\r\n");
      out.write("			                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/SearchBook/searchBookAll.jsp\">모든 도서 보기</a></li>\r\n");
      out.write("			                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/SearchBook/searchBookByBtitle.jsp\">제목별 검색</a></li>\r\n");
      out.write("			                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/SearchBook/searchBookByCategory.jsp\">카테고리별 검색</a></li>\r\n");
      out.write("			                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/SearchBook/searchBookMost.jsp\">베스트셀러</a></li>\r\n");
      out.write("			                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/SearchBook/searchBookNew.jsp\">신간</a></li>\r\n");
      out.write("			            </ul>\r\n");
      out.write("			        </li>\r\n");
      out.write("			        <li class=\"menu-item\">\r\n");
      out.write("			            <a href=\"#\">나의 도서관</a>\r\n");
      out.write("			            <ul class=\"submenu\">\r\n");
      out.write("			                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/BorrowBook/borrowList.jsp\">내 대출 도서 보기</a></li>\r\n");
      out.write("			                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/ReserveBook/reserveList.jsp\">내 예약 도서 보기</a></li>\r\n");
      out.write("			            </ul>\r\n");
      out.write("			        </li>\r\n");
      out.write("            <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/article/articleList.jsp\">묻고답하기</a>\r\n");
      out.write("                <ul class=\"submenu\">                   \r\n");
      out.write("                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/article/articleList.jsp\">묻고답하기</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("			        <li class=\"menu-item\">\r\n");
      out.write("			            <a href=\"#\">내 정보</a>\r\n");
      out.write("			            <ul class=\"submenu\">\r\n");
      out.write("			                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/ManageAccount/showMyAccount.jsp?password=");
      out.print( password );
      out.write("\">내 정보 보기</a></li>\r\n");
      out.write("			                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/ManageAccount/updateMyAccount.jsp\">내 정보 수정</a></li>\r\n");
      out.write("			                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/ManageAccount/deleteMyAccount.jsp\">회원 탈퇴</a></li>\r\n");
      out.write("			            </ul>\r\n");
      out.write("			        </li>\r\n");
      out.write("			    </ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</body>\r\n");
      out.write("	\r\n");
      out.write("	");
  } else { 
	if(id.equals("admin")) {
	System.out.println("session으로 설정한 adminid : " + id);
	
      out.write("      \r\n");
      out.write("<body align=\"center\">\r\n");
      out.write("<table align=\"center\" width=\"70%\">\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td width = 25%>\r\n");
      out.write("        	<a href=\"");
      out.print( request.getContextPath() );
      out.write("/main.jsp\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/image/도서관이미지.jpg\" id=\"library-image\" width=\"100%\"></a>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td align=\"center\" id=\"search-container\">\r\n");
      out.write("        	 <form action=\"");
      out.print( request.getContextPath() );
      out.write("/user/SearchBook/searchBookByBtitle.jsp\">\r\n");
      out.write("                <input type=\"text\" name=\"btitle2\">\r\n");
      out.write("                <input type=\"submit\" id=\"searchByBtitle\" value=\"검색\">\r\n");
      out.write("            </form>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td class=\"user-name\">");
      out.print( mname );
      out.write("님</td>\r\n");
      out.write("        <td><a href=\"");
      out.print( request.getContextPath() );
      out.write("/login/logout.jsp\" class=\"logout-button\">로그아웃</a></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"menu-container\">\r\n");
      out.write("        <ul class=\"menu-list\">\r\n");
      out.write("\r\n");
      out.write("            <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/ManageBook/showBook.jsp\">도서</a>\r\n");
      out.write("                <ul class=\"submenu\">\r\n");
      out.write("                    <li><a href = \"");
      out.print( request.getContextPath() );
      out.write("/admin/ManageBook/showBook.jsp\">도서 관리</a></li>\r\n");
      out.write("                    <li><a href = \"");
      out.print( request.getContextPath() );
      out.write("/admin/ManageBook/insertBook.jsp\">도서 추가</a></li>\r\n");
      out.write("                    <li><a href = \"");
      out.print( request.getContextPath() );
      out.write("/admin/ManageBook/showBookByCategory.jsp\">카테고리별 도서 관리</a></li>\r\n");
      out.write("                    <li><a href = \"");
      out.print( request.getContextPath() );
      out.write("/admin/ManageBook/showBookByBpubyear.jsp\">연도별 도서 관리</a></li>                   \r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"menu-item\">\r\n");
      out.write("                <a href = \"");
      out.print( request.getContextPath() );
      out.write("/admin/ManageMember/showMember.jsp\">회원 관리</a>\r\n");
      out.write("                <ul class=\"submenu\">\r\n");
      out.write("                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/ManageMember/showMember.jsp\">회원 보기</a></li>\r\n");
      out.write("                    \r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/article/articleList.jsp\">묻고답하기</a>\r\n");
      out.write("                <ul class=\"submenu\">                   \r\n");
      out.write("                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/article/articleList.jsp\">묻고답하기</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"#\">내 정보</a>\r\n");
      out.write("                <ul class=\"submenu\">\r\n");
      out.write("                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/ManageAccount/showMyAccount.jsp?password=");
      out.print( password );
      out.write("\">내 정보 보기</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/ManageAccount/updateMyAccount.jsp\">내 정보 수정</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/ManageAccount/deleteMyAccount.jsp\">회원 탈퇴</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("	");
 } else {
	System.out.println("session으로 설정한 id : " + id);
	
      out.write("      \r\n");
      out.write("		<body align = \"center\">\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("<table align=\"center\" width=\"70%\">\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td width = 25%>\r\n");
      out.write("        	<a href=\"");
      out.print( request.getContextPath() );
      out.write("/main.jsp\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/image/도서관이미지.jpg\" id=\"library-image\" width=\"100%\"></a>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td align=\"center\" id=\"search-container\">\r\n");
      out.write("        	 <form action=\"");
      out.print( request.getContextPath() );
      out.write("/user/SearchBook/searchBookByBtitle.jsp\">\r\n");
      out.write("                <input type=\"text\" name=\"btitle2\">\r\n");
      out.write("                <input type=\"submit\" id=\"searchByBtitle\" value=\"검색\">\r\n");
      out.write("            </form>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td class=\"user-name\">");
      out.print( mname );
      out.write("님</td>\r\n");
      out.write("        <td><a href=\"");
      out.print( request.getContextPath() );
      out.write("/login/logout.jsp\" class=\"logout-button\">로그아웃</a></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("	\r\n");
      out.write("<div class=\"menu-container\">\r\n");
      out.write("    <ul class=\"menu-list\">\r\n");
      out.write("\r\n");
      out.write("        <li class=\"menu-item\">\r\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/SearchBook/searchBookAll.jsp\">도서</a>\r\n");
      out.write("            <ul class=\"submenu\">\r\n");
      out.write("                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/SearchBook/searchBookAll.jsp\">모든 도서 보기</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/SearchBook/searchBookByBtitle.jsp\">제목별 검색</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/SearchBook/searchBookByCategory.jsp\">카테고리별 검색</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/SearchBook/searchBookMost.jsp\">베스트셀러</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/SearchBook/searchBookNew.jsp\">신간</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"menu-item\">\r\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/BorrowBook/borrowList.jsp\">나의 도서관</a>\r\n");
      out.write("            <ul class=\"submenu\">\r\n");
      out.write("                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/BorrowBook/borrowList.jsp\">내 대출 도서 보기</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/ReserveBook/reserveList.jsp\">내 예약 도서 보기</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("            <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/article/articleList.jsp\">묻고답하기</a>\r\n");
      out.write("                <ul class=\"submenu\">                   \r\n");
      out.write("                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/article/articleList.jsp\">묻고답하기</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("        <li class=\"menu-item\">\r\n");
      out.write("            <a href=\"#\">내 정보</a>\r\n");
      out.write("            <ul class=\"submenu\">\r\n");
      out.write("                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/ManageAccount/showMyAccount.jsp?password=");
      out.print( password );
      out.write("\">내 정보 보기</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/ManageAccount/updateMyAccount.jsp\">내 정보 수정</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/ManageAccount/deleteMyAccount.jsp\">회원 탈퇴</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("</div>\r\n");
      out.write("		</body>\r\n");
      out.write("	");
 }
	}

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/script.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("    $('input[type = submit]').click(function(){\r\n");
      out.write("        var mname = $('input[name = mname]').val();\r\n");
      out.write("        var rrn1 = $('input[name = rrn1]').val();\r\n");
      out.write("        var rrn2 = $('input[name = rrn2]').val();\r\n");
      out.write("        \r\n");
      out.write("        if(mname == \"\") {\r\n");
      out.write("            alert(\"이름 누락\");\r\n");
      out.write("            $('input[name = mname]').focus();\r\n");
      out.write("            return false;\r\n");
      out.write("        } else if(rrn1 == \"\") {\r\n");
      out.write("            alert(\"주민등록번호 앞자리 누락\");\r\n");
      out.write("            $('input[name = rrn1]').focus();\r\n");
      out.write("            return false;\r\n");
      out.write("        } else if(rrn2 == \"\") {\r\n");
      out.write("            alert(\"주민등록번호 뒷자리 누락\");\r\n");
      out.write("            $('input[name = rrn2]').focus();\r\n");
      out.write("            return false;\r\n");
      out.write("        } else if(rrn1.length !== 6 || isNaN(rrn1)) {\r\n");
      out.write("            alert(\"주민등록번호 앞자리는 6자리 숫자여야 합니다.\");\r\n");
      out.write("            $('input[name = rrn1]').select();\r\n");
      out.write("            return false;\r\n");
      out.write("        } else if(rrn2.length !== 7 || isNaN(rrn2)) {\r\n");
      out.write("            alert(\"주민등록번호 뒷자리는 7자리 숫자여야 합니다.\");\r\n");
      out.write("            $('input[name = rrn2]').select();\r\n");
      out.write("            return false;\r\n");
      out.write("        } \r\n");
      out.write("        \r\n");
      out.write("    }); //submit 클릭\r\n");
      out.write("}); //ready\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("    /* 테이블 스타일 */\r\n");
      out.write("    .form-table {\r\n");
      out.write("        border-collapse: collapse;\r\n");
      out.write("        width: 50%;\r\n");
      out.write("        margin: auto; /* 테이블 가운데 정렬 */\r\n");
      out.write("    }\r\n");
      out.write("    .form-table th, .form-table td {\r\n");
      out.write("        border: 1px solid #ddd;\r\n");
      out.write("        padding: 8px;\r\n");
      out.write("        text-align: left;\r\n");
      out.write("    }\r\n");
      out.write("    .form-table input[type=\"text\"], \r\n");
      out.write("    .form-table input[type=\"password\"] {\r\n");
      out.write("        padding: 8px;\r\n");
      out.write("        width: 40%; /* 주민등록번호 입력 필드가 한 줄에 나오도록 조정 */\r\n");
      out.write("        box-sizing: border-box; /* 입력 필드의 내부 패딩까지 포함하여 너비 설정 */\r\n");
      out.write("    }\r\n");
      out.write("    .form-table input[type=\"submit\"] {\r\n");
      out.write("        padding: 10px 20px;\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        margin: 5px;\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        background-color: #007bff; /* 파란색 */\r\n");
      out.write("        color: white;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        transition: background-color 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("    .form-table input[type=\"submit\"]:hover {\r\n");
      out.write("        background-color: #0056b3; /* 파란색 어둡게 */\r\n");
      out.write("    }\r\n");
      out.write("    .form-table input[type=\"reset\"] {\r\n");
      out.write("        padding: 10px 20px;\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        margin: 5px;\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        background-color: #6c757d; /* 회색 */\r\n");
      out.write("        color: white;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        transition: background-color 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("    .form-table input[type=\"reset\"]:hover {\r\n");
      out.write("        background-color: #495057; /* 회색 어둡게 */\r\n");
      out.write("    }\r\n");
      out.write("    .form-table input[type=\"button\"] {\r\n");
      out.write("        padding: 10px 20px;\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        margin: 5px;\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        background-color: #28a745; /* 초록색 */\r\n");
      out.write("        color: white;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        transition: background-color 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("    .form-table input[type=\"button\"]:hover {\r\n");
      out.write("        background-color: #218838; /* 초록색 어둡게 */\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form action=\"findIdProc.jsp\" method=\"post\">\r\n");
      out.write("    <table class=\"form-table\" border=\"1\">\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>이름</td>\r\n");
      out.write("            <td><input type=\"text\" name=\"mname\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>주민등록번호</td>\r\n");
      out.write("            <td>\r\n");
      out.write("                <input type=\"text\" name=\"rrn1\" maxlength=\"6\"> - \r\n");
      out.write("                <input type=\"password\" name=\"rrn2\" maxlength=\"7\">\r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td colspan=\"2\" align=\"center\">\r\n");
      out.write("                <input type=\"submit\" value=\"확인\">\r\n");
      out.write("                <input type=\"reset\" value=\"취소\">\r\n");
      out.write("                <input type=\"button\" value=\"돌아가기\">\r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <style>\r\n");
      out.write("        table {\r\n");
      out.write("            width: 90%;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            border-collapse: collapse;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        td {\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .footer-text {\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            line-height: 1.5;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .copyright {\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("            color: #888;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<table>\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td colspan=\"2\" align=\"center\">\r\n");
      out.write("            <p class=\"footer-text\">\r\n");
      out.write("                서울특별시 영등포구 의사당대로 1 (여의도동) (우07233)<br>\r\n");
      out.write("                홈페이지 관련 문의 webw3@nanet.go.kr<br>\r\n");
      out.write("                전화문의 02-6788-4211(수신자 부담)\r\n");
      out.write("            </p>\r\n");
      out.write("        </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td colspan=\"2\" align=\"center\" class=\"copyright\">\r\n");
      out.write("            Copyright ⓒ 대한민국 국회도서관 All rights reserved.\r\n");
      out.write("        </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
