/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-04-01 02:44:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import myPkg.MemberBean;

public final class Ex03_005fresult_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(1);
    _jspx_imports_classes.add("myPkg.MemberBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("Ex03_result.jsp<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("UTF-8");
	String id = request.getParameter("id");
	String pw = request.getParameter("pw");
	String name = request.getParameter("name");
	String mclass = request.getParameter("mclass");
	String phone1 = request.getParameter("phone1");
	String phone2 = request.getParameter("phone2");
	String phone3 = request.getParameter("phone2");

      out.write('\r');
      out.write('\n');

	MemberBean mb1 = new MemberBean();
	mb1.setId(id);
	mb1.setPw(pw);
	mb1.setName(name);
	mb1.setMclass(mclass);
	mb1.setPhone1(phone1);
	mb1.setPhone2(phone2);
	mb1.setPhone3(phone3);
	
	String temp; //비교는 jsp여도 java코드 사용해야 함
	if(mb1.getMclass().equals("1")) {
		temp = "비회원";
	} else if(mb1.getMclass().equals("2")) {
		temp = "정회원";
	} else if(mb1.getMclass().equals("3")) {
		temp = "우수회원";
	} else {
		temp = "관리자";
	}
	
	out.print("아이디 : " + mb1.getId()+"<br>"); 
	out.print("비밀번호 : " + mb1.getPw()+"<br>"); 
	out.print("회원이름 : " + mb1.getName()+"<br>"); 
	out.print("회원구분 : " + mb1.getMclass()+"/"+temp+"<br>"); 
	out.print("전화번호 : " + mb1.getPhone1()+"-"+ mb1.getPhone2()+"-"+mb1.getPhone3()); 


      out.write("\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      myPkg.MemberBean mb2 = null;
      mb2 = (myPkg.MemberBean) _jspx_page_context.getAttribute("mb2", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (mb2 == null){
        mb2 = new myPkg.MemberBean();
        _jspx_page_context.setAttribute("mb2", mb2, javax.servlet.jsp.PageContext.PAGE_SCOPE);
        out.write('\r');
        out.write('\n');
        out.write('	');
        org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("mb2"), "id", request.getParameter("id"), request, "id", false);
        out.write('\r');
        out.write('\n');
        out.write('	');
        org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("mb2"), "pw", request.getParameter("pw"), request, "pw", false);
        out.write('\r');
        out.write('\n');
        out.write('	');
        org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("mb2"), "name", request.getParameter("name"), request, "name", false);
        out.write('\r');
        out.write('\n');
        out.write('	');
        org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("mb2"), "mclass", request.getParameter("mclass"), request, "mclass", false);
        out.write('\r');
        out.write('\n');
        out.write('	');
        org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("mb2"), "phone1", request.getParameter("phone1"), request, "phone1", false);
        out.write('\r');
        out.write('\n');
        out.write('	');
        org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("mb2"), "phone2", request.getParameter("phone2"), request, "phone2", false);
        out.write('\r');
        out.write('\n');
        out.write('	');
        org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("mb2"), "phone3", request.getParameter("phone3"), request, "phone3", false);
        out.write('\r');
        out.write('\n');
      }
      out.write("\r\n");
      out.write("\r\n");

	//비교는 jsp여도 java코드 사용해야 함
	if(mb2.getMclass().equals("1")) {
		temp = "비회원";
	} else if(mb2.getMclass().equals("2")) {
		temp = "정회원";
	} else if(mb2.getMclass().equals("3")) {
		temp = "우수회원";
	} else {
		temp = "관리자";
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("아이디 : ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((myPkg.MemberBean)_jspx_page_context.findAttribute("mb2")).getId())));
      out.write("<br>\r\n");
      out.write("비밀번호 : ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((myPkg.MemberBean)_jspx_page_context.findAttribute("mb2")).getPw())));
      out.write("<br>\r\n");
      out.write("회원이름 : ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((myPkg.MemberBean)_jspx_page_context.findAttribute("mb2")).getName())));
      out.write("<br>\r\n");
      out.write("회원구분 : ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((myPkg.MemberBean)_jspx_page_context.findAttribute("mb2")).getMclass())));
      out.write('/');
      out.print( temp );
      out.write("<br>\r\n");
      out.write("전화번호 : ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((myPkg.MemberBean)_jspx_page_context.findAttribute("mb2")).getPhone1())));
      out.write('-');
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((myPkg.MemberBean)_jspx_page_context.findAttribute("mb2")).getPhone2())));
      out.write('-');
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((myPkg.MemberBean)_jspx_page_context.findAttribute("mb2")).getPhone3())));
      out.write("\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      myPkg.MemberBean mb3 = null;
      mb3 = (myPkg.MemberBean) _jspx_page_context.getAttribute("mb3", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (mb3 == null){
        mb3 = new myPkg.MemberBean();
        _jspx_page_context.setAttribute("mb3", mb3, javax.servlet.jsp.PageContext.PAGE_SCOPE);
        out.write('\r');
        out.write('\n');
        out.write('	');
        org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("mb3"), request);
        out.write('\r');
        out.write('\n');
      }
      out.write("\r\n");
      out.write("\r\n");

	//비교는 jsp여도 java코드 사용해야 함
	if(mb3.getMclass().equals("1")) {
		temp = "비회원";
	} else if(mb3.getMclass().equals("2")) {
		temp = "정회원";
	} else if(mb3.getMclass().equals("3")) {
		temp = "우수회원";
	} else {
		temp = "관리자";
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("아이디 : ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((myPkg.MemberBean)_jspx_page_context.findAttribute("mb3")).getId())));
      out.write("<br>\r\n");
      out.write("비밀번호 : ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((myPkg.MemberBean)_jspx_page_context.findAttribute("mb3")).getPw())));
      out.write("<br>\r\n");
      out.write("회원이름 : ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((myPkg.MemberBean)_jspx_page_context.findAttribute("mb3")).getName())));
      out.write("<br>\r\n");
      out.write("회원구분 : ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((myPkg.MemberBean)_jspx_page_context.findAttribute("mb3")).getMclass())));
      out.write('/');
      out.print( temp );
      out.write("<br>\r\n");
      out.write("전화번호 : ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((myPkg.MemberBean)_jspx_page_context.findAttribute("mb3")).getPhone1())));
      out.write('-');
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((myPkg.MemberBean)_jspx_page_context.findAttribute("mb3")).getPhone2())));
      out.write('-');
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((myPkg.MemberBean)_jspx_page_context.findAttribute("mb3")).getPhone3())));
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
