/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-04-01 08:02:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import myPkg.Ex06_Bean_이예원;

public final class Ex06_005fresult_005f이예원_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(1);
    _jspx_imports_classes.add("myPkg.Ex06_Bean_이예원");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("Ex06_result_이예원.jsp<br>\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("UTF-8");
	String title = request.getParameter("title");
	String author = request.getParameter("author");
	String publisher = request.getParameter("publisher");
	String price = request.getParameter("price");
	String date = request.getParameter("date");
	String kind = request.getParameter("kind");
	String[] bookstore = request.getParameterValues("bookstore");
	String count = request.getParameter("count");

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table border = 1>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<th>제목</th>\r\n");
      out.write("		<td>");
      out.print( title );
      out.write("</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<th>저자</th>\r\n");
      out.write("		<td>");
      out.print( author );
      out.write("</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("\r\n");
      out.write("	<tr>\r\n");
      out.write("		<th>출판사</th>\r\n");
      out.write("		<td>");
      out.print( publisher );
      out.write("</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("\r\n");
      out.write("	<tr>\r\n");
      out.write("		<th>가격</th>\r\n");
      out.write("		<td>");
      out.print( price );
      out.write("</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("\r\n");
      out.write("	<tr>\r\n");
      out.write("		<th>입고일</th>\r\n");
      out.write("		<td>");
      out.print( date );
      out.write("</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("\r\n");
      out.write("	<tr>\r\n");
      out.write("		<th>배송비</th>\r\n");
      out.write("		<td>");
      out.print( kind );
      out.write("</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("\r\n");
      out.write("	<tr>\r\n");
      out.write("		<th>구입가능 서점</th>\r\n");
      out.write("		<td>\r\n");
      out.write("		");

		if(bookstore == null) {
				out.print("입고 서점 없음");
			} else {
				for (int i = 0; i < bookstore.length; i++) {
					out.print(bookstore[i] + " ");
				}
			}
		
      out.write("\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<th>보유수량</th>\r\n");
      out.write("		<td>");
      out.print( count );
      out.write("</td>\r\n");
      out.write("	</tr>	\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Ex06_Bean_이예원 ex = new Ex06_Bean_이예원();
	ex.setTitle(title);
	ex.setAuthor(author);
	ex.setPublisher(publisher);
	ex.setPrice(price);
	ex.setDate(date);
	ex.setKind(kind);
	ex.setBookstore(bookstore);
	ex.setCount(count);
	

      out.write("\r\n");
      out.write("<table border = 1>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<th>제목</th>\r\n");
      out.write("		<td>");
      out.print( ex.getTitle() );
      out.write("</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<th>저자</th>\r\n");
      out.write("		<td>");
      out.print( ex.getAuthor() );
      out.write("</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("\r\n");
      out.write("	<tr>\r\n");
      out.write("		<th>출판사</th>\r\n");
      out.write("		<td>");
      out.print( ex.getPublisher() );
      out.write("</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("\r\n");
      out.write("	<tr>\r\n");
      out.write("		<th>가격</th>\r\n");
      out.write("		<td>");
      out.print( ex.getPrice() );
      out.write("</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("\r\n");
      out.write("	<tr>\r\n");
      out.write("		<th>입고일</th>\r\n");
      out.write("		<td>");
      out.print( ex.getDate() );
      out.write("</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("\r\n");
      out.write("	<tr>\r\n");
      out.write("		<th>배송비</th>\r\n");
      out.write("		<td>");
      out.print( ex.getKind() );
      out.write("</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("\r\n");
      out.write("	<tr>\r\n");
      out.write("		<th>구입가능 서점</th>\r\n");
      out.write("		<td>\r\n");
      out.write("		");

		if(bookstore == null) {
				out.print("입고 서점 없음");
			} else {
				for (int i = 0; i < bookstore.length; i++) {
					out.print(bookstore[i] + " ");
				}
			}
		
      out.write("\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<th>보유수량</th>\r\n");
      out.write("		<td>");
      out.print( ex.getCount() );
      out.write("</td>\r\n");
      out.write("	</tr>	\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      myPkg.Ex06_Bean_이예원 ex2 = null;
      ex2 = (myPkg.Ex06_Bean_이예원) _jspx_page_context.getAttribute("ex2", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (ex2 == null){
        ex2 = new myPkg.Ex06_Bean_이예원();
        _jspx_page_context.setAttribute("ex2", ex2, javax.servlet.jsp.PageContext.PAGE_SCOPE);
        out.write('\r');
        out.write('\n');
        out.write('	');
        org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("ex2"), "title", request.getParameter("title"), request, "title", false);
        out.write('\r');
        out.write('\n');
        out.write('	');
        org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("ex2"), "author", request.getParameter("author"), request, "author", false);
        out.write('\r');
        out.write('\n');
        out.write('	');
        org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("ex2"), "publisher", request.getParameter("publisher"), request, "publisher", false);
        out.write('\r');
        out.write('\n');
        out.write('	');
        org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("ex2"), "price", request.getParameter("price"), request, "price", false);
        out.write('\r');
        out.write('\n');
        out.write('	');
        org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("ex2"), "date", request.getParameter("date"), request, "date", false);
        out.write('\r');
        out.write('\n');
        out.write('	');
        org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("ex2"), "kind", request.getParameter("kind"), request, "kind", false);
        out.write('\r');
        out.write('\n');
        out.write('	');
        org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("ex2"), "bookstore", request.getParameter("bookstore"), request, "bookstore", false);
        out.write('\r');
        out.write('\n');
        out.write('	');
        org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("ex2"), "count", request.getParameter("count"), request, "count", false);
        out.write('\r');
        out.write('\n');
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table border = 1>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<th>제목</th>\r\n");
      out.write("		<td>");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((myPkg.Ex06_Bean_이예원)_jspx_page_context.findAttribute("ex2")).getTitle())));
      out.write("</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<th>저자</th>\r\n");
      out.write("		<td>");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((myPkg.Ex06_Bean_이예원)_jspx_page_context.findAttribute("ex2")).getAuthor())));
      out.write("</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("\r\n");
      out.write("	<tr>\r\n");
      out.write("		<th>출판사</th>\r\n");
      out.write("		<td>");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((myPkg.Ex06_Bean_이예원)_jspx_page_context.findAttribute("ex2")).getPublisher())));
      out.write("</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("\r\n");
      out.write("	<tr>\r\n");
      out.write("		<th>가격</th>\r\n");
      out.write("		<td>");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((myPkg.Ex06_Bean_이예원)_jspx_page_context.findAttribute("ex2")).getPrice())));
      out.write("</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("\r\n");
      out.write("	<tr>\r\n");
      out.write("		<th>입고일</th>\r\n");
      out.write("		<td>");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((myPkg.Ex06_Bean_이예원)_jspx_page_context.findAttribute("ex2")).getDate())));
      out.write("</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("\r\n");
      out.write("	<tr>\r\n");
      out.write("		<th>배송비</th>\r\n");
      out.write("		<td>");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((myPkg.Ex06_Bean_이예원)_jspx_page_context.findAttribute("ex2")).getKind())));
      out.write("</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("\r\n");
      out.write("	<tr>\r\n");
      out.write("		<th>구입가능 서점</th>\r\n");
      out.write("		<td>\r\n");
      out.write("		");

		if(bookstore == null) {
				out.print("입고 서점 없음");
			} else {
				for (int i = 0; i < bookstore.length; i++) {
					out.print(bookstore[i] + " ");
				}
			}
		
      out.write("\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<th>보유수량</th>\r\n");
      out.write("		<td>");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((myPkg.Ex06_Bean_이예원)_jspx_page_context.findAttribute("ex2")).getCount())));
      out.write("</td>\r\n");
      out.write("	</tr>	\r\n");
      out.write("\r\n");
      out.write("</table>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
