/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-04-22 05:06:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.myshop.display;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.DecimalFormat;
import my.shop.ProductBean;
import java.util.Vector;
import my.shop.CategoryBean;
import java.util.ArrayList;
import my.shop.CategoryDao;

public final class mall_005fcartList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/myshop/display/mall_top.jsp", Long.valueOf(1713762135425L));
    _jspx_dependants.put("/myshop/display/mall_bottom.jsp", Long.valueOf(1713410776267L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("java.util.Vector");
    _jspx_imports_classes.add("my.shop.CategoryDao");
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("my.shop.ProductBean");
    _jspx_imports_classes.add("my.shop.CategoryBean");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("mall_cartList.jsp<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("mall_top.jsp<br>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/style.css\" type = \"text/css\"/>\r\n");
      out.write("<style>\r\n");
      out.write("	body{\r\n");
      out.write("		text-align : center;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.logout{\r\n");
      out.write("		float : right;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");

	String contextPath = request.getContextPath();
	CategoryDao cdao = CategoryDao.getInstance();
	ArrayList<CategoryBean> clist = cdao.getAllCategory();
	String memid = (String)session.getAttribute("memid");
	

      out.write("\r\n");
      out.write("<table border = 1>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td colspan = \"2\" align = \"center\" height = \"50\">\r\n");
      out.write("			<a href = \"");
      out.print( contextPath );
      out.write("/main.jsp\"> Home </a>|\r\n");
      out.write("			");

				if(memid.equals("admin")) {
			
      out.write("		<a href = \"");
      out.print( contextPath );
      out.write("/myshop/admin/main.jsp\"> 관리자홈 	</a>|\r\n");
      out.write("			");
	} 
			
      out.write("\r\n");
      out.write("			\r\n");
      out.write("			<a href = \"");
      out.print( contextPath );
      out.write("/myshop/display/mall.jsp\"> 쇼핑몰홈 </a> |\r\n");
      out.write("			<a href = \"");
      out.print( contextPath );
      out.write("/myshop/display/mall_cartList.jsp\"> 장바구니 </a>|\r\n");
      out.write("			<a href = \"");
      out.print( contextPath );
      out.write("/myshop/board/list.jsp\"> 게시판 </a>|\r\n");
      out.write("			<a href = \"");
      out.print( contextPath );
      out.write("/myshop/display/company.jsp\"> 회사소개 </a>|\r\n");
      out.write("			<span class = \"logout\"> ");
      out.print( memid );
      out.write("님  </span>\r\n");
      out.write("			<a class = \"logout\" href = \"");
      out.print( contextPath );
      out.write("/logout.jsp\">\r\n");
      out.write("				<img src = \"");
      out.print( contextPath );
      out.write("/img/logout3.jpg\" width = \"50\">\r\n");
      out.write("			</a>		\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("		\r\n");
      out.write("	<tr width = \"20%\">\r\n");
      out.write("		<td valign = \"top\">\r\n");
      out.write("			<table border = 1 >\r\n");
      out.write("				<caption>카테고리</caption>\r\n");
      out.write("					");


						if(clist.size() == 0) {
					
      out.write("\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td> 카테고리 없음 </td>\r\n");
      out.write("							</tr>\r\n");
      out.write("					");
	} else {
							for(CategoryBean cb : clist) {
					
      out.write("		<tr>\r\n");
      out.write("								<td><a href = \"");
      out.print( contextPath );
      out.write("/myshop/display/mall_cgList.jsp?code=");
      out.print(cb.getCode());
      out.write("&cname=");
      out.print(cb.getCname());
      out.write('"');
      out.write('>');
      out.print( cb.getCname() );
      out.write('[');
      out.print( cb.getCode() );
      out.write("] </a> </td>\r\n");
      out.write("							</tr>\r\n");
      out.write("								\r\n");
      out.write("					");
		}
						}	
					
      out.write("		\r\n");
      out.write("\r\n");
      out.write("			</table>\r\n");
      out.write("		</td>\r\n");
      out.write("		\r\n");
      out.write("		<td width = \"600px\" align = \"center\" valign = \"top\">\r\n");
      out.write("     \r\n");
      my.shop.mall.CartBean mallCart = null;
      synchronized (session) {
        mallCart = (my.shop.mall.CartBean) _jspx_page_context.getAttribute("mallCart", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (mallCart == null){
          mallCart = new my.shop.mall.CartBean();
          _jspx_page_context.setAttribute("mallCart", mallCart, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("<!-- 한번 만든 객체를 계속 사용하고 싶으면 아이디가 동일해야 함 -->\r\n");

	Vector<ProductBean> cartList = mallCart.getAllProducts();
	DecimalFormat df = new DecimalFormat("###,###");

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table border = 1>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td colspan = \"6\" align = \"center\">\r\n");
      out.write("			<h4>장바구니 보기</h4>\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	\r\n");
      out.write("	<tr class = \"m1\" align = \"center\">\r\n");
      out.write("		<td width = \"10%\">번호</td>\r\n");
      out.write("		<td width = \"20%\">상품명</td>\r\n");
      out.write("		<td width = \"20%\">수량</td>\r\n");
      out.write("		<td width = \"20%\">단가</td>\r\n");
      out.write("		<td width = \"20%\">금액</td>\r\n");
      out.write("		<td width = \"10%\">삭제</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("\r\n");

	int cartTotalPrice = 0;
	int cartTotalPoint = 0;
	if(cartList.size() == 0) {

      out.write("		<tr align = \"center\">\r\n");
      out.write("			<td colspan = 6> 장바구니에 담긴 상품이 없습니다.</td>\r\n");
      out.write("		</tr>\r\n");
	} else {
		for(ProductBean pb : cartList) {

      out.write("			<tr align = \"center\">\r\n");
      out.write("			<td>");
      out.print( pb.getPnum() );
      out.write("</td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<img src=\"");
      out.print( request.getContextPath()+"/myshop/images/"+pb.getPimage());
      out.write("\" width=\"120\" height=\"80\"><br>\r\n");
      out.write("				");
      out.print( pb.getPname() );
      out.write("\r\n");
      out.write("			</td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<form name = \"f\" method = \"post\" action = \"mall_cartEdit.jsp\">\r\n");
      out.write("					<input type = \"hidden\" name = \"pnum\" value = ");
      out.print( pb.getPnum() );
      out.write(">   \r\n");
      out.write("					<input type = \"text\" name = \"oqty\" value = \"");
      out.print( pb.getPqty() );
      out.write("\" size = 2>개\r\n");
      out.write("					<input type = \"submit\" value = \"수정\">\r\n");
      out.write("				</form>\r\n");
      out.write("			</td>\r\n");
      out.write("			<td align = \"right\">\r\n");
      out.write("				");
      out.print( df.format(pb.getPrice()) );
      out.write("원<br>\r\n");
      out.write("				[");
      out.print( df.format(pb.getPoint()) );
      out.write("] point\r\n");
      out.write("			</td>\r\n");
      out.write("			<td align = \"right\">\r\n");
      out.write("			");
      out.print( df.format(pb.getPrice() * pb.getPqty()) );
      out.write("원<br>\r\n");
      out.write("			[");
      out.print( df.format(pb.getPoint() * pb.getPqty()) );
      out.write("] point\r\n");
      out.write("			</td>\r\n");
      out.write("			<td><a href = \"mall_cartDel.jsp?pnum=");
      out.print( pb.getPnum() );
      out.write("\">삭제</a></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		\r\n");
      out.write("		");
 
		cartTotalPrice += pb.getPrice() * pb.getPqty();
		cartTotalPoint += pb.getPoint() * pb.getPqty();
		
      out.write('\r');
      out.write('\n');
		}
	}

      out.write("		\r\n");
      out.write("	<tr class = m1>\r\n");
      out.write("		<td colspan = 4 align = \"center\">\r\n");
      out.write("			<b>장바구니 총액 : </b>\r\n");
      out.write("			<font color = \"red\">");
      out.print( df.format(cartTotalPrice) );
      out.write(" 원</font><br>\r\n");
      out.write("			<b>총 적립 포인트 : </b>\r\n");
      out.write("			<font color = \"green\">[");
      out.print( df.format(cartTotalPoint) );
      out.write("] point</font>\r\n");
      out.write("		</td>\r\n");
      out.write("		<td colspan = 2 align = \"center\">\r\n");
      out.write("			<a href = \"mall_order.jsp\">[주문하기]</a>\r\n");
      out.write("			[계속 쇼핑]\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr height = \"40\" align = \"center\">\r\n");
      out.write("	<td colspan = \"2\">\r\n");
      out.write("		mall_bottom.jsp<br>\r\n");
      out.write("		서비스 약관 | 광고안내 | 제휴문의 | 고객센터 | 찾아오시는 길\r\n");
      out.write("	</td>\r\n");
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("</table>");
      out.write("     ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
