/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-04-18 06:07:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.myshop.display;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import my.shop.CategoryBean;
import java.util.ArrayList;
import my.shop.CategoryDao;

public final class mall_005ftop_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("my.shop.CategoryDao");
    _jspx_imports_classes.add("my.shop.CategoryBean");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("mall_top.jsp<br>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/style.css\" type = \"text/css\"/>\r\n");
      out.write("<style>\r\n");
      out.write("	body{\r\n");
      out.write("		text-align : center;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.logout{\r\n");
      out.write("		float : right;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");

	String contextPath = request.getContextPath();
	CategoryDao cdao = CategoryDao.getInstance();
	ArrayList<CategoryBean> clist = cdao.getAllCategory();
	String memid = (String)session.getAttribute("memid");
	

      out.write("\r\n");
      out.write("<table border = 1>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td colspan = \"2\" align = \"center\" height = \"50\">\r\n");
      out.write("			<a href = \"");
      out.print( contextPath );
      out.write("/main.jsp\"> Home </a>|\r\n");
      out.write("			");

				if(memid.equals("admin")) {
			
      out.write("		<a href = \"");
      out.print( contextPath );
      out.write("/myshop/admin/main.jsp\"> 관리자홈 	</a>|\r\n");
      out.write("			");
	} 
			
      out.write("\r\n");
      out.write("			\r\n");
      out.write("			<a href = \"");
      out.print( contextPath );
      out.write("/myshop/display/mall.jsp\"> 쇼핑몰홈 </a> |\r\n");
      out.write("			<a> 장바구니 </a>|\r\n");
      out.write("			<a> 게시판 </a>|\r\n");
      out.write("			<a> 회사소개 </a>|\r\n");
      out.write("			<span class = \"logout\"> ");
      out.print( memid );
      out.write("님  </span>\r\n");
      out.write("			<a class = \"logout\"><img src = \"");
      out.print( contextPath );
      out.write("/img/logout.jpg\" width = \"50\"></a>		\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("		\r\n");
      out.write("	<tr width = \"20%\">\r\n");
      out.write("		<td valign = \"top\">\r\n");
      out.write("			<table border = 1 >\r\n");
      out.write("				<caption>카테고리</caption>\r\n");
      out.write("					");


						if(clist.size() == 0) {
					
      out.write("\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td> 카테고리 없음 </td>\r\n");
      out.write("							</tr>\r\n");
      out.write("					");
	} else {
							for(CategoryBean cb : clist) {
					
      out.write("		<tr>\r\n");
      out.write("								<td><a href = \"");
      out.print( contextPath );
      out.write("/myshop/display/mall_cgList.jsp?code=");
      out.print(cb.getCode());
      out.write("&cname=");
      out.print(cb.getCname());
      out.write('"');
      out.write('>');
      out.print( cb.getCname() );
      out.write('[');
      out.print( cb.getCode() );
      out.write("] </a> </td>\r\n");
      out.write("							</tr>\r\n");
      out.write("								\r\n");
      out.write("					");
		}
						}	
					
      out.write("		\r\n");
      out.write("\r\n");
      out.write("			</table>\r\n");
      out.write("		</td>\r\n");
      out.write("		\r\n");
      out.write("		<td width = \"600px\" align = \"center\" valign = \"top\">\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
