/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-05-08 09:57:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.article;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import article.ArticleDao;
import member.MemberDao;

public final class deleteArticle_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/article/../../top.jsp", Long.valueOf(1715160700093L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("member.MemberDao");
    _jspx_imports_classes.add("article.ArticleDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("deleteArticle.jsp<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/script.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("    $('#searchByBtitle').click(function(){\r\n");
      out.write("        var btitle = $('input[name = btitle]').val();\r\n");
      out.write("        \r\n");
      out.write("        if(btitle == \"\") {\r\n");
      out.write("            alert(\"검색하고 싶은 도서명을 입력하세요\");\r\n");
      out.write("            $('input[name = btitle]').focus();\r\n");
      out.write("            return false;\r\n");
      out.write("        } else {\r\n");
      out.write("            return true; // 입력값이 비어 있지 않으면 검색 동작 실행\r\n");
      out.write("        }\r\n");
      out.write("    }); //submit 클릭\r\n");
      out.write("}); //ready\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".menu-container {\r\n");
      out.write("    width: 90%;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-list {\r\n");
      out.write("    list-style: none;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    display: table;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-item {\r\n");
      out.write("    display: table-cell;\r\n");
      out.write("    margin-right: 20px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("    width: 20%; /* 각 항목의 너비를 20%로 설정 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-item a {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: #333;\r\n");
      out.write("    display: block;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    background-color: #f4f4f4;\r\n");
      out.write("    border: 1px solid #ccc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".submenu {\r\n");
      out.write("    display: none;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    background-color: #fff;\r\n");
      out.write("    border: 1px solid #ccc;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    width: 16.7%; /* 하위 목록의 너비를 100%로 설정 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-item:hover .submenu {\r\n");
      out.write("    display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".submenu li {\r\n");
      out.write("    display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".submenu li a {\r\n");
      out.write("    display: block;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".submenu li a:hover {\r\n");
      out.write("    background-color: #f4f4f4;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#search-container {\r\n");
      out.write("    width: 60%; /* 전체 너비의 90%로 설정 */\r\n");
      out.write("    margin: 0 auto; /* 가운데 정렬을 위해 왼쪽과 오른쪽에 자동 마진 추가 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#search-container input[type=\"text\"] {\r\n");
      out.write("    width: 80%; /* 검색 칸의 너비를 80%로 설정 */\r\n");
      out.write("    padding: 10px; /* 내부 여백 추가 */\r\n");
      out.write("    font-size: 16px; /* 글꼴 크기 설정 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#search-container input[type=\"submit\"] {\r\n");
      out.write("    width: 15%; /* 검색 버튼의 너비를 15%로 설정 */\r\n");
      out.write("    padding: 10px; /* 내부 여백 추가 */\r\n");
      out.write("    font-size: 16px; /* 글꼴 크기 설정 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#search-container img {\r\n");
      out.write("    max-width:15%; /* 이미지의 최대 너비를 전체의 25%로 설정 */\r\n");
      out.write("    height: auto; /* 가로 세로 비율을 유지하면서 이미지의 높이를 자동으로 조정 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 로그아웃 버튼 스타일 */\r\n");
      out.write(".login-button, .logout-button, .register-button {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    border: none;\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-button {\r\n");
      out.write("    background-color: #4CAF50;\r\n");
      out.write("    color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-button:hover {\r\n");
      out.write("    background-color: #45a049;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logout-button {\r\n");
      out.write("    background-color: #f44336;\r\n");
      out.write("    color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logout-button:hover {\r\n");
      out.write("    background-color: #d32f2f;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".register-button {\r\n");
      out.write("    background-color: #2196F3;\r\n");
      out.write("    color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".register-button:hover {\r\n");
      out.write("    background-color: #1e88e5;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".user-name {\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    color: #333;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("    .menu-container {\r\n");
      out.write("        font-family: Arial, sans-serif;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .menu-list {\r\n");
      out.write("        list-style-type: none;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .menu-item {\r\n");
      out.write("        background-color: #f8f9fa; /* 기본 배경색 */\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("        border-bottom: 1px solid #dee2e6;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .menu-item:hover {\r\n");
      out.write("        background-color: #e9ecef; /* 마우스 올릴 때 배경색 */\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .menu-item a {\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color: #212529;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .submenu {\r\n");
      out.write("        display: none;\r\n");
      out.write("        background-color: #fff;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        border: 1px solid #dee2e6;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .submenu li {\r\n");
      out.write("        padding: 8px 10px;\r\n");
      out.write("        border-bottom: 1px solid #dee2e6;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .submenu li:hover {\r\n");
      out.write("        background-color: #f8f9fa; /* 마우스 올릴 때 배경색 */\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .menu-item:hover .submenu {\r\n");
      out.write("        display: block;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");

	String id = (String)session.getAttribute("id");
	String password = (String)session.getAttribute("password");
	String mname = (String)session.getAttribute("mname");
	
	MemberDao mdao = MemberDao.getInstance();
	int mnum = mdao.findmnum(id);
	
	if(id == null) {
	    System.out.println("<top.jsp> null");

      out.write("      \r\n");
      out.write("		<body align = \"center\">\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("			<table align=\"center\" width=\"80%\">\r\n");
      out.write("			    <tr>\r\n");
      out.write("			        <td width=\"25%\">\r\n");
      out.write("			            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/main.jsp\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/image/도서관이미지.jpg\" id=\"library-image\" width=\"100%\"></a>\r\n");
      out.write("			        </td>\r\n");
      out.write("			        <td align=\"center\" id=\"search-container\">\r\n");
      out.write("			            <form action=\"");
      out.print( request.getContextPath() );
      out.write("/user/SearchBook/searchBookByBtitle.jsp\">\r\n");
      out.write("			                <input type=\"text\" name=\"btitle2\">\r\n");
      out.write("			                <input type=\"submit\" id=\"searchByBtitle\" value=\"검색\">\r\n");
      out.write("			            </form>\r\n");
      out.write("			        </td>\r\n");
      out.write("			        <td>\r\n");
      out.write("			            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/login/login.jsp\" class=\"login-button\">로그인</a>\r\n");
      out.write("			        </td>\r\n");
      out.write("			        <td>\r\n");
      out.write("			            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/ManageAccount/canIInsert.jsp\" class=\"register-button\">회원가입</a>\r\n");
      out.write("			        </td>\r\n");
      out.write("			    </tr>\r\n");
      out.write("			</table>\r\n");
      out.write("\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"menu-container\">\r\n");
      out.write("			    <ul class=\"menu-list\">\r\n");
      out.write("\r\n");
      out.write("			        <li class=\"menu-item\">\r\n");
      out.write("			            <a href=\"#\">도서</a>\r\n");
      out.write("			            <ul class=\"submenu\">\r\n");
      out.write("			                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/SearchBook/searchBookAll.jsp\">모든 도서 보기</a></li>\r\n");
      out.write("			                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/SearchBook/searchBookByBtitle.jsp\">제목별 검색</a></li>\r\n");
      out.write("			                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/SearchBook/searchBookByCategory.jsp\">카테고리별 검색</a></li>\r\n");
      out.write("			                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/SearchBook/searchBookMost.jsp\">베스트셀러</a></li>\r\n");
      out.write("			                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/SearchBook/searchBookNew.jsp\">신간</a></li>\r\n");
      out.write("			            </ul>\r\n");
      out.write("			        </li>\r\n");
      out.write("			        <li class=\"menu-item\">\r\n");
      out.write("			            <a href=\"#\">나의 도서관</a>\r\n");
      out.write("			            <ul class=\"submenu\">\r\n");
      out.write("			                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/BorrowBook/borrowList.jsp\">내 대출 도서 보기</a></li>\r\n");
      out.write("			                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/ReserveBook/reserveList.jsp\">내 예약 도서 보기</a></li>\r\n");
      out.write("			            </ul>\r\n");
      out.write("			        </li>\r\n");
      out.write("            <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/article/articleList.jsp\">묻고답하기</a>\r\n");
      out.write("                <ul class=\"submenu\">                   \r\n");
      out.write("                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/article/articleList.jsp\">묻고답하기</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("			        <li class=\"menu-item\">\r\n");
      out.write("			            <a href=\"#\">내 정보</a>\r\n");
      out.write("			            <ul class=\"submenu\">\r\n");
      out.write("			                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/ManageAccount/showMyAccount.jsp?password=");
      out.print( password );
      out.write("\">내 정보 보기</a></li>\r\n");
      out.write("			                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/ManageAccount/updateMyAccount.jsp\">내 정보 수정</a></li>\r\n");
      out.write("			                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/ManageAccount/deleteMyAccount.jsp\">회원 탈퇴</a></li>\r\n");
      out.write("			            </ul>\r\n");
      out.write("			        </li>\r\n");
      out.write("			    </ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</body>\r\n");
      out.write("	\r\n");
      out.write("	");
  } else { 
	if(id.equals("admin")) {
	System.out.println("session으로 설정한 adminid : " + id);
	
      out.write("      \r\n");
      out.write("<body align=\"center\">\r\n");
      out.write("<table align=\"center\" width=\"70%\">\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td width = 25%>\r\n");
      out.write("        	<a href=\"");
      out.print( request.getContextPath() );
      out.write("/main.jsp\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/image/도서관이미지.jpg\" id=\"library-image\" width=\"100%\"></a>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td align=\"center\" id=\"search-container\">\r\n");
      out.write("        	 <form action=\"");
      out.print( request.getContextPath() );
      out.write("/user/SearchBook/searchBookByBtitle.jsp\">\r\n");
      out.write("                <input type=\"text\" name=\"btitle2\">\r\n");
      out.write("                <input type=\"submit\" id=\"searchByBtitle\" value=\"검색\">\r\n");
      out.write("            </form>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td class=\"user-name\">");
      out.print( mname );
      out.write("님</td>\r\n");
      out.write("        <td><a href=\"");
      out.print( request.getContextPath() );
      out.write("/login/logout.jsp\" class=\"logout-button\">로그아웃</a></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"menu-container\">\r\n");
      out.write("        <ul class=\"menu-list\">\r\n");
      out.write("\r\n");
      out.write("            <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/ManageBook/showBook.jsp\">도서</a>\r\n");
      out.write("                <ul class=\"submenu\">\r\n");
      out.write("                    <li><a href = \"");
      out.print( request.getContextPath() );
      out.write("/admin/ManageBook/showBook.jsp\">도서 관리</a></li>\r\n");
      out.write("                    <li><a href = \"");
      out.print( request.getContextPath() );
      out.write("/admin/ManageBook/insertBook.jsp\">도서 추가</a></li>\r\n");
      out.write("                    <li><a href = \"");
      out.print( request.getContextPath() );
      out.write("/admin/ManageBook/showBookByCategory.jsp\">카테고리별 도서 관리</a></li>\r\n");
      out.write("                    <li><a href = \"");
      out.print( request.getContextPath() );
      out.write("/admin/ManageBook/showBookByBpubyear.jsp\">연도별 도서 관리</a></li>                   \r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"menu-item\">\r\n");
      out.write("                <a href = \"");
      out.print( request.getContextPath() );
      out.write("/admin/ManageMember/showMember.jsp\">회원 관리</a>\r\n");
      out.write("                <ul class=\"submenu\">\r\n");
      out.write("                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/ManageMember/showMember.jsp\">회원 보기</a></li>\r\n");
      out.write("                    \r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/article/articleList.jsp\">묻고답하기</a>\r\n");
      out.write("                <ul class=\"submenu\">                   \r\n");
      out.write("                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/article/articleList.jsp\">묻고답하기</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"#\">내 정보</a>\r\n");
      out.write("                <ul class=\"submenu\">\r\n");
      out.write("                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/ManageAccount/showMyAccount.jsp?password=");
      out.print( password );
      out.write("\">내 정보 보기</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/ManageAccount/updateMyAccount.jsp\">내 정보 수정</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/ManageAccount/deleteMyAccount.jsp\">회원 탈퇴</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("	");
 } else {
	System.out.println("session으로 설정한 id : " + id);
	
      out.write("      \r\n");
      out.write("		<body align = \"center\">\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("<table align=\"center\" width=\"70%\">\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td width = 25%>\r\n");
      out.write("        	<a href=\"");
      out.print( request.getContextPath() );
      out.write("/main.jsp\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/image/도서관이미지.jpg\" id=\"library-image\" width=\"100%\"></a>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td align=\"center\" id=\"search-container\">\r\n");
      out.write("        	 <form action=\"");
      out.print( request.getContextPath() );
      out.write("/user/SearchBook/searchBookByBtitle.jsp\">\r\n");
      out.write("                <input type=\"text\" name=\"btitle2\">\r\n");
      out.write("                <input type=\"submit\" id=\"searchByBtitle\" value=\"검색\">\r\n");
      out.write("            </form>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td class=\"user-name\">");
      out.print( mname );
      out.write("님</td>\r\n");
      out.write("        <td><a href=\"");
      out.print( request.getContextPath() );
      out.write("/login/logout.jsp\" class=\"logout-button\">로그아웃</a></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("	\r\n");
      out.write("<div class=\"menu-container\">\r\n");
      out.write("    <ul class=\"menu-list\">\r\n");
      out.write("\r\n");
      out.write("        <li class=\"menu-item\">\r\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/SearchBook/searchBookAll.jsp\">도서</a>\r\n");
      out.write("            <ul class=\"submenu\">\r\n");
      out.write("                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/SearchBook/searchBookAll.jsp\">모든 도서 보기</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/SearchBook/searchBookByBtitle.jsp\">제목별 검색</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/SearchBook/searchBookByCategory.jsp\">카테고리별 검색</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/SearchBook/searchBookMost.jsp\">베스트셀러</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/SearchBook/searchBookNew.jsp\">신간</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"menu-item\">\r\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/BorrowBook/borrowList.jsp\">나의 도서관</a>\r\n");
      out.write("            <ul class=\"submenu\">\r\n");
      out.write("                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/BorrowBook/borrowList.jsp\">내 대출 도서 보기</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/ReserveBook/reserveList.jsp\">내 예약 도서 보기</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("            <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/article/articleList.jsp\">묻고답하기</a>\r\n");
      out.write("                <ul class=\"submenu\">                   \r\n");
      out.write("                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/article/articleList.jsp\">묻고답하기</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("        <li class=\"menu-item\">\r\n");
      out.write("            <a href=\"#\">내 정보</a>\r\n");
      out.write("            <ul class=\"submenu\">\r\n");
      out.write("                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/ManageAccount/showMyAccount.jsp?password=");
      out.print( password );
      out.write("\">내 정보 보기</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/ManageAccount/updateMyAccount.jsp\">내 정보 수정</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/ManageAccount/deleteMyAccount.jsp\">회원 탈퇴</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("</div>\r\n");
      out.write("		</body>\r\n");
      out.write("	");
 }
	}

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

	request.setCharacterEncoding("UTF-8");

	int anum = Integer.parseInt(request.getParameter("anum"));
	int pageNum = Integer.parseInt(request.getParameter("pageNum"));
	String aname = request.getParameter("aname");
	
	System.out.println("<deleteArticle.jsp> anum : " + anum + ", pageNum : " + pageNum + ", aname : " + aname);
	
	ArticleDao adao = ArticleDao.getInstance();
	int count = adao.getArticleCount();
	int pageSize = 10;
	int pageCount = count / pageSize + (count % pageSize == 0 ? 0 : 1);
	
	String msg = null;
	String url = null;
	
	boolean flag = adao.canIDeleteThisArticle(anum);
	
	if(mname.equals("관리자")) {
		//관리자는 무조건 삭제 가능
		int cnt = adao.deleteArticle(anum);
		if(cnt > 0) {
			msg = "delete 성공";
			if(pageCount < pageNum) {
				pageNum = pageCount;
			}
			url = "articleList.jsp?pageNum=" + pageNum;			
		} else {
			msg = "delete 실패";
			url = "showArticle.jsp?anum=" + anum + "&pageNum=" + pageNum;
		}
		
	} else if(aname.equals(mname)) {
		//내 글
		if(flag == true) {
			//답글 아직 안 달렸음
			int cnt = adao.deleteArticle(anum);
			if(cnt > 0) {
				msg = "delete 성공";
				if(pageCount < pageNum) {
					pageNum = pageCount;
				}
				url = "articleList.jsp?pageNum=" + pageNum;			
			} else {
				msg = "delete 실패";
				url = "showArticle.jsp?anum=" + anum + "&pageNum=" + pageNum;
			}
		} else {
			//답글 달려서 삭제 못함
			msg = "이미 답글이 달린 게시글은 삭제할 수 없습니다.";
			url = "showArticle.jsp?anum=" + anum + "&pageNum=" + pageNum;
		}
	} else {
		//내 글 아님
		msg = "삭제 권한이 없습니다.";
		url = "showArticle.jsp?anum=" + anum + "&pageNum=" + pageNum;
	}
	
	

      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		alert(\"");
      out.print( msg );
      out.write("\");\r\n");
      out.write("		location.href = '");
      out.print( url );
      out.write("';\r\n");
      out.write("	</script> ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
