/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-04-16 00:36:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.myshop.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("myshop\\member\\register.jsp<br>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/script.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<form action = \"registerPro.jsp\" name = \"myform\" method = \"post\" onSubmit = \"return writeSave()\">\r\n");
      out.write("	<table border=\"1\" align = \"center\">\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td colspan = \"2\" bgcolor = \"#ffcc00\" align = \"center\">\r\n");
      out.write("				<font size = \"3\" color = \"#5d1900\"> ◈ 기본정보 ◈ </font>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td bgcolor = \"yellow\" align = \"center\">* 회원 아이디</td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<input type = \"text\" name = \"id\" maxlength = \"10\">\r\n");
      out.write("				<input type = \"button\" value = \"중복체크\" onClick = \"duplicate()\">\r\n");
      out.write("				<span id = \"idmessage\"></span>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td bgcolor = \"yellow\" align = \"center\">* 비밀 번호</td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<input type = \"password\" name = \"password\" maxlength = \"16\" onBlur = \"return pwcheck()\">\r\n");
      out.write("				영문 소문자/숫자 조합 3~8자\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td bgcolor=\"yellow\" align=\"center\">* 비밀 번호 확인</td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<input type=\"password\" name=\"repassword\" maxlength=\"16\" onKeyUp = \"repasswordCheck()\">\r\n");
      out.write("				<span id = \"pwmessage\"></span>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td bgcolor=\"yellow\" align=\"center\">E-Mail</td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<input type=\"text\" name=\"email\">\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td colspan=\"2\" bgcolor=\"#ffcc00\">\r\n");
      out.write("				<font size=\"3\" color=\"#5d1900\">◈ 개인 신상 정보 ◈</font>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td bgcolor=\"yellow\" align=\"center\">한글 이름</td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<input type=\"text\" name=\"name\" value=\"홍길동\">\r\n");
      out.write("				성과 이름을 붙여주세요 (예)홍길동\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td bgcolor=\"yellow\" align=\"center\">주민 등록 번호</td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<input type=\"text\" name=\"num1\" value=\"123456\"> -\r\n");
      out.write("				<input type=\"text\" name=\"num2\" value=\"1234567\">\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td bgcolor=\"yellow\" align=\"center\">휴대 전화 번호</td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<select name=\"phone1\">\r\n");
      out.write("					<option value=\"010\">010\r\n");
      out.write("					<option value=\"011\">011\r\n");
      out.write("					<option value=\"051\">051\r\n");
      out.write("				</select>\r\n");
      out.write("				-\r\n");
      out.write("				<input type=\"text\" name=\"phone2\" size=\"4\" value=\"1234\"> -\r\n");
      out.write("				<input type=\"text\" name=\"phone3\" size=\"4\" value=\"5678\">\r\n");
      out.write("				예)011-000-0000\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td bgcolor=\"yellow\" align=\"center\">가입 일자</td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<input type=\"text\" name=\"reg_date\" value=\"2020/01/01\">\r\n");
      out.write("				예)2000/05/22\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td colspan=\"2\" bgcolor=\"#ffcc00\" align=\"center\">\r\n");
      out.write("				<input type=\"submit\" value=\"가입하기\">\r\n");
      out.write("				<input type=\"button\" value=\"취소\">\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("</form>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
